name: Upload Python Package

on:
  push:
    branches:
    - 'main'
    paths: 
    - 'version.py'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python3 -m pip install --upgrade pip
        python3 -m pip install build twine
        python3 -m pip install --no-warn-script-location -r requirements.txt
    - name: Run unit tests
      run: python3 -m unittest
    - name: Build module
      run: python3 -m build
    - name: Publish module on PyPi
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 -m twine upload dist/*
